"""Sync schema with models

Revision ID: ed43e94f99a2
Revises: 001_initial
Create Date: 2026-04-09 23:16:21.414871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed43e94f99a2'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_documents_id'), 'reference_documents', ['id'], unique=False)
    op.add_column('submissions', sa.Column('question_paper_path', sa.String(length=500), nullable=True))
    op.add_column('submissions', sa.Column('question_paper_original_filename', sa.String(length=255), nullable=True))
    op.add_column('total_results', sa.Column('ai_report_card', sa.Text(), nullable=True))
    op.drop_index(op.f('email'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.drop_column('total_results', 'ai_report_card')
    op.drop_column('submissions', 'question_paper_original_filename')
    op.drop_column('submissions', 'question_paper_path')
    op.drop_index(op.f('ix_reference_documents_id'), table_name='reference_documents')
    op.drop_table('reference_documents')
    # ### end Alembic commands ###
